### PR TITLE
add new column with default value and migration script

### PR DESCRIPTION
**Pull request by mybigopenbox**
# What and why?
secure messages to be routed to the correct teams, so that resourcing can be sufficiently arranged to cover all queries

# How to test?
deploy into environment and validate by viewing the database table

# Trello
S32 User account creation - Background functionality to route secure messages

### CODE REVIEW

**Review by warrenbailey — CHANGES_REQUESTED** [review]
@mybigopenbox are the migration scripts missing from this PR as I can't see them?

Also for any new messages that are created we need to default the category to 'SURVEY' for now, I'd imagine that'll be done somewhere in the python code

**Comment by mybigopenbox** [comment]
changes done.
two files 004_add_field_category_on_secure_message.sql and database.py within secure message both having a default value of 'SURVEY'

**Comment by warrenbailey** [comment]
Great thanks 👍

**Review by warrenbailey — APPROVED** [review]

**Comment by warrenbailey** [comment]
Approved, though it might be good to have a unit test. Then we can expand the tests once the new categories arrive.

**Review by warrenbailey — APPROVED** [review]

**Pull request merged**
